package com.powerwin.entity;

public class CallbackTableDemo {
    public CallbackTableDemo() {
    }

    public CallbackTableDemo(Integer id, Short action, Short saved, Short isBoolMonitor, Integer gameId, Integer uid, Integer appid, Integer cid, Integer adplanid, Integer adid, Integer adFrom, Integer dataFrom, String udid, String sys, String version, String userAgent, String ip, Float income, Integer appuserid, Integer areaTime, Integer createTime, Integer ucid) {
        this.id = id;
        this.action = action;
        this.saved = saved;
        this.isBoolMonitor = isBoolMonitor;
        this.gameId = gameId;
        this.uid = uid;
        this.appid = appid;
        this.cid = cid;
        this.adplanid = adplanid;
        this.adid = adid;
        this.adFrom = adFrom;
        this.dataFrom = dataFrom;
        this.udid = udid;
        this.sys = sys;
        this.version = version;
        this.userAgent = userAgent;
        this.ip = ip;
        this.income = income;
        this.appuserid = appuserid;
        this.areaTime = areaTime;
        this.createTime = createTime;
        this.ucid = ucid;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.id
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.action
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Short action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.saved
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Short saved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.is_bool_monitor
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Short isBoolMonitor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.game_id
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Integer gameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.uid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.appid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Integer appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.cid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.adplanid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Integer adplanid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.adid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Integer adid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.ad_from
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Integer adFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.data_from
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Integer dataFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.udid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private String udid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.sys
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private String sys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.version
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.user_agent
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private String userAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.ip
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.income
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Float income;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.appuserid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Integer appuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.area_time
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Integer areaTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.create_time
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_callback_20180711.ucid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    private Integer ucid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.id
     *
     * @return the value of cpc_callback_20180711.id
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.id
     *
     * @param id the value for cpc_callback_20180711.id
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.action
     *
     * @return the value of cpc_callback_20180711.action
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Short getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.action
     *
     * @param action the value for cpc_callback_20180711.action
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setAction(Short action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.saved
     *
     * @return the value of cpc_callback_20180711.saved
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Short getSaved() {
        return saved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.saved
     *
     * @param saved the value for cpc_callback_20180711.saved
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setSaved(Short saved) {
        this.saved = saved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.is_bool_monitor
     *
     * @return the value of cpc_callback_20180711.is_bool_monitor
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Short getIsBoolMonitor() {
        return isBoolMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.is_bool_monitor
     *
     * @param isBoolMonitor the value for cpc_callback_20180711.is_bool_monitor
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setIsBoolMonitor(Short isBoolMonitor) {
        this.isBoolMonitor = isBoolMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.game_id
     *
     * @return the value of cpc_callback_20180711.game_id
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.game_id
     *
     * @param gameId the value for cpc_callback_20180711.game_id
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.uid
     *
     * @return the value of cpc_callback_20180711.uid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.uid
     *
     * @param uid the value for cpc_callback_20180711.uid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.appid
     *
     * @return the value of cpc_callback_20180711.appid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.appid
     *
     * @param appid the value for cpc_callback_20180711.appid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.cid
     *
     * @return the value of cpc_callback_20180711.cid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.cid
     *
     * @param cid the value for cpc_callback_20180711.cid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.adplanid
     *
     * @return the value of cpc_callback_20180711.adplanid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Integer getAdplanid() {
        return adplanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.adplanid
     *
     * @param adplanid the value for cpc_callback_20180711.adplanid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setAdplanid(Integer adplanid) {
        this.adplanid = adplanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.adid
     *
     * @return the value of cpc_callback_20180711.adid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Integer getAdid() {
        return adid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.adid
     *
     * @param adid the value for cpc_callback_20180711.adid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setAdid(Integer adid) {
        this.adid = adid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.ad_from
     *
     * @return the value of cpc_callback_20180711.ad_from
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Integer getAdFrom() {
        return adFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.ad_from
     *
     * @param adFrom the value for cpc_callback_20180711.ad_from
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setAdFrom(Integer adFrom) {
        this.adFrom = adFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.data_from
     *
     * @return the value of cpc_callback_20180711.data_from
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Integer getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.data_from
     *
     * @param dataFrom the value for cpc_callback_20180711.data_from
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setDataFrom(Integer dataFrom) {
        this.dataFrom = dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.udid
     *
     * @return the value of cpc_callback_20180711.udid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public String getUdid() {
        return udid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.udid
     *
     * @param udid the value for cpc_callback_20180711.udid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setUdid(String udid) {
        this.udid = udid == null ? null : udid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.sys
     *
     * @return the value of cpc_callback_20180711.sys
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public String getSys() {
        return sys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.sys
     *
     * @param sys the value for cpc_callback_20180711.sys
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setSys(String sys) {
        this.sys = sys == null ? null : sys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.version
     *
     * @return the value of cpc_callback_20180711.version
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.version
     *
     * @param version the value for cpc_callback_20180711.version
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.user_agent
     *
     * @return the value of cpc_callback_20180711.user_agent
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.user_agent
     *
     * @param userAgent the value for cpc_callback_20180711.user_agent
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.ip
     *
     * @return the value of cpc_callback_20180711.ip
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.ip
     *
     * @param ip the value for cpc_callback_20180711.ip
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.income
     *
     * @return the value of cpc_callback_20180711.income
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Float getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.income
     *
     * @param income the value for cpc_callback_20180711.income
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setIncome(Float income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.appuserid
     *
     * @return the value of cpc_callback_20180711.appuserid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Integer getAppuserid() {
        return appuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.appuserid
     *
     * @param appuserid the value for cpc_callback_20180711.appuserid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setAppuserid(Integer appuserid) {
        this.appuserid = appuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.area_time
     *
     * @return the value of cpc_callback_20180711.area_time
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Integer getAreaTime() {
        return areaTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.area_time
     *
     * @param areaTime the value for cpc_callback_20180711.area_time
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setAreaTime(Integer areaTime) {
        this.areaTime = areaTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.create_time
     *
     * @return the value of cpc_callback_20180711.create_time
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.create_time
     *
     * @param createTime the value for cpc_callback_20180711.create_time
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_callback_20180711.ucid
     *
     * @return the value of cpc_callback_20180711.ucid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public Integer getUcid() {
        return ucid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_callback_20180711.ucid
     *
     * @param ucid the value for cpc_callback_20180711.ucid
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    public void setUcid(Integer ucid) {
        this.ucid = ucid;
    }
}