package com.powerwin.entity;

public class CpcHour {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.id
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.created
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.year
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Short year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.mon
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Short mon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.day
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Short day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.hour
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Short hour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.type
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.data_from
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Short dataFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.ad_from
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Short adFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.show_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer showCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.show_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer showInvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.show_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer showUnique;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.show_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer showSaved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.click_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer clickCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.click_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer clickInvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.click_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer clickUnique;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.click_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer clickSaved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.jump_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jumpCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.jump_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jumpInvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.jump_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jumpUnique;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.jump_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jumpSaved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.active_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer activeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.active_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer activeInvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.active_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer activeUnique;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.active_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer activeSaved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jobCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_count1
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jobCount1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_count2
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jobCount2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_count3
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jobCount3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_count4
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jobCount4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_count5
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jobCount5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_count6
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jobCount6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_count7
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jobCount7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_count8
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jobCount8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_count9
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jobCount9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jobInvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jobUnique;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Integer jobSaved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.click_income
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Float clickIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.click_cost
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Float clickCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.active_income
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Float activeIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.active_cost
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Float activeCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_income
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Float jobIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.job_cost
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Float jobCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpc_hour.game_id
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    private Short gameId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.id
     *
     * @return the value of cpc_hour.id
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.id
     *
     * @param id the value for cpc_hour.id
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.created
     *
     * @return the value of cpc_hour.created
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.created
     *
     * @param created the value for cpc_hour.created
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.year
     *
     * @return the value of cpc_hour.year
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Short getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.year
     *
     * @param year the value for cpc_hour.year
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setYear(Short year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.mon
     *
     * @return the value of cpc_hour.mon
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Short getMon() {
        return mon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.mon
     *
     * @param mon the value for cpc_hour.mon
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setMon(Short mon) {
        this.mon = mon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.day
     *
     * @return the value of cpc_hour.day
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Short getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.day
     *
     * @param day the value for cpc_hour.day
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setDay(Short day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.hour
     *
     * @return the value of cpc_hour.hour
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Short getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.hour
     *
     * @param hour the value for cpc_hour.hour
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setHour(Short hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.type
     *
     * @return the value of cpc_hour.type
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.type
     *
     * @param type the value for cpc_hour.type
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.data_from
     *
     * @return the value of cpc_hour.data_from
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Short getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.data_from
     *
     * @param dataFrom the value for cpc_hour.data_from
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setDataFrom(Short dataFrom) {
        this.dataFrom = dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.ad_from
     *
     * @return the value of cpc_hour.ad_from
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Short getAdFrom() {
        return adFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.ad_from
     *
     * @param adFrom the value for cpc_hour.ad_from
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setAdFrom(Short adFrom) {
        this.adFrom = adFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.show_count
     *
     * @return the value of cpc_hour.show_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getShowCount() {
        return showCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.show_count
     *
     * @param showCount the value for cpc_hour.show_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setShowCount(Integer showCount) {
        this.showCount = showCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.show_invalid
     *
     * @return the value of cpc_hour.show_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getShowInvalid() {
        return showInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.show_invalid
     *
     * @param showInvalid the value for cpc_hour.show_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setShowInvalid(Integer showInvalid) {
        this.showInvalid = showInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.show_unique
     *
     * @return the value of cpc_hour.show_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getShowUnique() {
        return showUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.show_unique
     *
     * @param showUnique the value for cpc_hour.show_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setShowUnique(Integer showUnique) {
        this.showUnique = showUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.show_saved
     *
     * @return the value of cpc_hour.show_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getShowSaved() {
        return showSaved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.show_saved
     *
     * @param showSaved the value for cpc_hour.show_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setShowSaved(Integer showSaved) {
        this.showSaved = showSaved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.click_count
     *
     * @return the value of cpc_hour.click_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getClickCount() {
        return clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.click_count
     *
     * @param clickCount the value for cpc_hour.click_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setClickCount(Integer clickCount) {
        this.clickCount = clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.click_invalid
     *
     * @return the value of cpc_hour.click_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getClickInvalid() {
        return clickInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.click_invalid
     *
     * @param clickInvalid the value for cpc_hour.click_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setClickInvalid(Integer clickInvalid) {
        this.clickInvalid = clickInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.click_unique
     *
     * @return the value of cpc_hour.click_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getClickUnique() {
        return clickUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.click_unique
     *
     * @param clickUnique the value for cpc_hour.click_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setClickUnique(Integer clickUnique) {
        this.clickUnique = clickUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.click_saved
     *
     * @return the value of cpc_hour.click_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getClickSaved() {
        return clickSaved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.click_saved
     *
     * @param clickSaved the value for cpc_hour.click_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setClickSaved(Integer clickSaved) {
        this.clickSaved = clickSaved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.jump_count
     *
     * @return the value of cpc_hour.jump_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJumpCount() {
        return jumpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.jump_count
     *
     * @param jumpCount the value for cpc_hour.jump_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJumpCount(Integer jumpCount) {
        this.jumpCount = jumpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.jump_invalid
     *
     * @return the value of cpc_hour.jump_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJumpInvalid() {
        return jumpInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.jump_invalid
     *
     * @param jumpInvalid the value for cpc_hour.jump_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJumpInvalid(Integer jumpInvalid) {
        this.jumpInvalid = jumpInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.jump_unique
     *
     * @return the value of cpc_hour.jump_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJumpUnique() {
        return jumpUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.jump_unique
     *
     * @param jumpUnique the value for cpc_hour.jump_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJumpUnique(Integer jumpUnique) {
        this.jumpUnique = jumpUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.jump_saved
     *
     * @return the value of cpc_hour.jump_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJumpSaved() {
        return jumpSaved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.jump_saved
     *
     * @param jumpSaved the value for cpc_hour.jump_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJumpSaved(Integer jumpSaved) {
        this.jumpSaved = jumpSaved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.active_count
     *
     * @return the value of cpc_hour.active_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getActiveCount() {
        return activeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.active_count
     *
     * @param activeCount the value for cpc_hour.active_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setActiveCount(Integer activeCount) {
        this.activeCount = activeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.active_invalid
     *
     * @return the value of cpc_hour.active_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getActiveInvalid() {
        return activeInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.active_invalid
     *
     * @param activeInvalid the value for cpc_hour.active_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setActiveInvalid(Integer activeInvalid) {
        this.activeInvalid = activeInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.active_unique
     *
     * @return the value of cpc_hour.active_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getActiveUnique() {
        return activeUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.active_unique
     *
     * @param activeUnique the value for cpc_hour.active_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setActiveUnique(Integer activeUnique) {
        this.activeUnique = activeUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.active_saved
     *
     * @return the value of cpc_hour.active_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getActiveSaved() {
        return activeSaved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.active_saved
     *
     * @param activeSaved the value for cpc_hour.active_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setActiveSaved(Integer activeSaved) {
        this.activeSaved = activeSaved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_count
     *
     * @return the value of cpc_hour.job_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJobCount() {
        return jobCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_count
     *
     * @param jobCount the value for cpc_hour.job_count
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobCount(Integer jobCount) {
        this.jobCount = jobCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_count1
     *
     * @return the value of cpc_hour.job_count1
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJobCount1() {
        return jobCount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_count1
     *
     * @param jobCount1 the value for cpc_hour.job_count1
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobCount1(Integer jobCount1) {
        this.jobCount1 = jobCount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_count2
     *
     * @return the value of cpc_hour.job_count2
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJobCount2() {
        return jobCount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_count2
     *
     * @param jobCount2 the value for cpc_hour.job_count2
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobCount2(Integer jobCount2) {
        this.jobCount2 = jobCount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_count3
     *
     * @return the value of cpc_hour.job_count3
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJobCount3() {
        return jobCount3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_count3
     *
     * @param jobCount3 the value for cpc_hour.job_count3
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobCount3(Integer jobCount3) {
        this.jobCount3 = jobCount3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_count4
     *
     * @return the value of cpc_hour.job_count4
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJobCount4() {
        return jobCount4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_count4
     *
     * @param jobCount4 the value for cpc_hour.job_count4
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobCount4(Integer jobCount4) {
        this.jobCount4 = jobCount4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_count5
     *
     * @return the value of cpc_hour.job_count5
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJobCount5() {
        return jobCount5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_count5
     *
     * @param jobCount5 the value for cpc_hour.job_count5
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobCount5(Integer jobCount5) {
        this.jobCount5 = jobCount5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_count6
     *
     * @return the value of cpc_hour.job_count6
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJobCount6() {
        return jobCount6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_count6
     *
     * @param jobCount6 the value for cpc_hour.job_count6
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobCount6(Integer jobCount6) {
        this.jobCount6 = jobCount6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_count7
     *
     * @return the value of cpc_hour.job_count7
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJobCount7() {
        return jobCount7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_count7
     *
     * @param jobCount7 the value for cpc_hour.job_count7
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobCount7(Integer jobCount7) {
        this.jobCount7 = jobCount7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_count8
     *
     * @return the value of cpc_hour.job_count8
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJobCount8() {
        return jobCount8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_count8
     *
     * @param jobCount8 the value for cpc_hour.job_count8
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobCount8(Integer jobCount8) {
        this.jobCount8 = jobCount8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_count9
     *
     * @return the value of cpc_hour.job_count9
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJobCount9() {
        return jobCount9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_count9
     *
     * @param jobCount9 the value for cpc_hour.job_count9
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobCount9(Integer jobCount9) {
        this.jobCount9 = jobCount9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_invalid
     *
     * @return the value of cpc_hour.job_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJobInvalid() {
        return jobInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_invalid
     *
     * @param jobInvalid the value for cpc_hour.job_invalid
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobInvalid(Integer jobInvalid) {
        this.jobInvalid = jobInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_unique
     *
     * @return the value of cpc_hour.job_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJobUnique() {
        return jobUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_unique
     *
     * @param jobUnique the value for cpc_hour.job_unique
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobUnique(Integer jobUnique) {
        this.jobUnique = jobUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_saved
     *
     * @return the value of cpc_hour.job_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Integer getJobSaved() {
        return jobSaved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_saved
     *
     * @param jobSaved the value for cpc_hour.job_saved
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobSaved(Integer jobSaved) {
        this.jobSaved = jobSaved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.click_income
     *
     * @return the value of cpc_hour.click_income
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Float getClickIncome() {
        return clickIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.click_income
     *
     * @param clickIncome the value for cpc_hour.click_income
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setClickIncome(Float clickIncome) {
        this.clickIncome = clickIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.click_cost
     *
     * @return the value of cpc_hour.click_cost
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Float getClickCost() {
        return clickCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.click_cost
     *
     * @param clickCost the value for cpc_hour.click_cost
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setClickCost(Float clickCost) {
        this.clickCost = clickCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.active_income
     *
     * @return the value of cpc_hour.active_income
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Float getActiveIncome() {
        return activeIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.active_income
     *
     * @param activeIncome the value for cpc_hour.active_income
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setActiveIncome(Float activeIncome) {
        this.activeIncome = activeIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.active_cost
     *
     * @return the value of cpc_hour.active_cost
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Float getActiveCost() {
        return activeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.active_cost
     *
     * @param activeCost the value for cpc_hour.active_cost
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setActiveCost(Float activeCost) {
        this.activeCost = activeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_income
     *
     * @return the value of cpc_hour.job_income
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Float getJobIncome() {
        return jobIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_income
     *
     * @param jobIncome the value for cpc_hour.job_income
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobIncome(Float jobIncome) {
        this.jobIncome = jobIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.job_cost
     *
     * @return the value of cpc_hour.job_cost
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Float getJobCost() {
        return jobCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.job_cost
     *
     * @param jobCost the value for cpc_hour.job_cost
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setJobCost(Float jobCost) {
        this.jobCost = jobCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpc_hour.game_id
     *
     * @return the value of cpc_hour.game_id
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public Short getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpc_hour.game_id
     *
     * @param gameId the value for cpc_hour.game_id
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    public void setGameId(Short gameId) {
        this.gameId = gameId;
    }
}