package com.powerwin.entity;

public class Devuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.id
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.cpname
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private String cpname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.pwd
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.password
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.linkname
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private String linkname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.moblie
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private String moblie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.qqnumber
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private String qqnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.skype
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private String skype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.cname
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.caddress
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private String caddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.ywcard
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private String ywcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.ywcardpic
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private String ywcardpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.status
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.type
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.money
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private Float money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.finish_money
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private Float finishMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.userid
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.update_time
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private Integer updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.create_time
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.idcard
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.wxnumber
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private String wxnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.locks
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private Byte locks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devuser.state
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.id
     *
     * @return the value of devuser.id
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.id
     *
     * @param id the value for devuser.id
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.cpname
     *
     * @return the value of devuser.cpname
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public String getCpname() {
        return cpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.cpname
     *
     * @param cpname the value for devuser.cpname
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setCpname(String cpname) {
        this.cpname = cpname == null ? null : cpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.pwd
     *
     * @return the value of devuser.pwd
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.pwd
     *
     * @param pwd the value for devuser.pwd
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.password
     *
     * @return the value of devuser.password
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.password
     *
     * @param password the value for devuser.password
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.linkname
     *
     * @return the value of devuser.linkname
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public String getLinkname() {
        return linkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.linkname
     *
     * @param linkname the value for devuser.linkname
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setLinkname(String linkname) {
        this.linkname = linkname == null ? null : linkname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.moblie
     *
     * @return the value of devuser.moblie
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public String getMoblie() {
        return moblie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.moblie
     *
     * @param moblie the value for devuser.moblie
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setMoblie(String moblie) {
        this.moblie = moblie == null ? null : moblie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.qqnumber
     *
     * @return the value of devuser.qqnumber
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public String getQqnumber() {
        return qqnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.qqnumber
     *
     * @param qqnumber the value for devuser.qqnumber
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setQqnumber(String qqnumber) {
        this.qqnumber = qqnumber == null ? null : qqnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.skype
     *
     * @return the value of devuser.skype
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public String getSkype() {
        return skype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.skype
     *
     * @param skype the value for devuser.skype
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setSkype(String skype) {
        this.skype = skype == null ? null : skype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.cname
     *
     * @return the value of devuser.cname
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.cname
     *
     * @param cname the value for devuser.cname
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.caddress
     *
     * @return the value of devuser.caddress
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public String getCaddress() {
        return caddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.caddress
     *
     * @param caddress the value for devuser.caddress
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setCaddress(String caddress) {
        this.caddress = caddress == null ? null : caddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.ywcard
     *
     * @return the value of devuser.ywcard
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public String getYwcard() {
        return ywcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.ywcard
     *
     * @param ywcard the value for devuser.ywcard
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setYwcard(String ywcard) {
        this.ywcard = ywcard == null ? null : ywcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.ywcardpic
     *
     * @return the value of devuser.ywcardpic
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public String getYwcardpic() {
        return ywcardpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.ywcardpic
     *
     * @param ywcardpic the value for devuser.ywcardpic
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setYwcardpic(String ywcardpic) {
        this.ywcardpic = ywcardpic == null ? null : ywcardpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.status
     *
     * @return the value of devuser.status
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.status
     *
     * @param status the value for devuser.status
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.type
     *
     * @return the value of devuser.type
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.type
     *
     * @param type the value for devuser.type
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.money
     *
     * @return the value of devuser.money
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.money
     *
     * @param money the value for devuser.money
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.finish_money
     *
     * @return the value of devuser.finish_money
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public Float getFinishMoney() {
        return finishMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.finish_money
     *
     * @param finishMoney the value for devuser.finish_money
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setFinishMoney(Float finishMoney) {
        this.finishMoney = finishMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.userid
     *
     * @return the value of devuser.userid
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.userid
     *
     * @param userid the value for devuser.userid
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.update_time
     *
     * @return the value of devuser.update_time
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.update_time
     *
     * @param updateTime the value for devuser.update_time
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.create_time
     *
     * @return the value of devuser.create_time
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.create_time
     *
     * @param createTime the value for devuser.create_time
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.idcard
     *
     * @return the value of devuser.idcard
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.idcard
     *
     * @param idcard the value for devuser.idcard
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.wxnumber
     *
     * @return the value of devuser.wxnumber
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public String getWxnumber() {
        return wxnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.wxnumber
     *
     * @param wxnumber the value for devuser.wxnumber
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setWxnumber(String wxnumber) {
        this.wxnumber = wxnumber == null ? null : wxnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.locks
     *
     * @return the value of devuser.locks
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public Byte getLocks() {
        return locks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.locks
     *
     * @param locks the value for devuser.locks
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setLocks(Byte locks) {
        this.locks = locks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devuser.state
     *
     * @return the value of devuser.state
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devuser.state
     *
     * @param state the value for devuser.state
     *
     * @mbg.generated Mon Jul 09 17:35:39 CST 2018
     */
    public void setState(Byte state) {
        this.state = state;
    }
}