package com.powerwin.dao;

import com.powerwin.entity.CallbackTableDemo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CallbackTableDemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpc_callback_20180711
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpc_callback_20180711
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    int insert(@Param("tablename") StringBuffer tablename, @Param("record") CallbackTableDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpc_callback_20180711
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    CallbackTableDemo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpc_callback_20180711
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    List<CallbackTableDemo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpc_callback_20180711
     *
     * @mbg.generated Wed Jul 11 14:14:16 CST 2018
     */
    int updateByPrimaryKey(CallbackTableDemo record);
}