package com.powerwin.dao;

import com.powerwin.entity.CpcHour;

import java.util.List;

public interface CpcHourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpc_hour
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpc_hour
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    int insert(CpcHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpc_hour
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    CpcHour selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpc_hour
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    List<CpcHour> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpc_hour
     *
     * @mbg.generated Wed Jul 11 11:57:48 CST 2018
     */
    int updateByPrimaryKey(CpcHour record);
}